### PR TITLE
[WIP] Adds error handling to lost-grid

### PR DESCRIPTION
**Pull request by peterramsing**
#180 is what inspired this pull request.
- [ ] Adds Error Handling for invalid syntax within lost-grid

### CODE REVIEW

**Comment by peterramsing** [comment]
The method that I'm initially experimenting with just adds a large if/then wrapper around the actual code that does the lost-grid magic asking if the rules passed in match what would be valid rules. An error is then thrown like such:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: lost: /Users/peterramsing/Documents/npDevelopment/lostTesting/dev/main.css:3:5: "foo" is not valid lost-sytax for lost-utility: foo.
div {
    lost-utility: foo;
    ^
}
```

There is also tools like [postcss-reporter](https://github.com/postcss/postcss-reporter) that might be worth looking into.

# 

There is an issue regarding testing. Currently, the tests are just looking whether or not the input equals the output. Being this is an error, not an output, the tests aren't so straight forward.

@corysimmons Do you have any thoughts on the tests for this?

**Comment by corysimmons** [comment]
@wyze Care to chime in?

**Comment by wyze** [comment]
Sorry about the delay here. I cleared the notification and forgot to get back to it!

Testing is simple, just need to check if postcss throws when you pass something not valid. The tests seem basic as I created a method to wrap a majority of the testing since we were just comparing input to output.

Here is a test I added to `test/lost-utility.js`:

``` javascript
  it('throws when not valid value', function() {
    var processor = postcss([lost()]);

    expect(processor.process('a { lost-utility: notvalid }')).to.throw;
  });
```

And then just bring over the requires like they are in `test/check.js`.

My gist of the full `test/lost-utility.js` is here: https://gist.github.com/wyze/7f240bcd6deb985ec776

cc @peterramsing @corysimmons

**Comment by peterramsing** [comment]
@wyze Thanks for that! I'll see what I can get sorted tomorrow.

**Comment by peterramsing** [comment]
I'm closing this PR as I need to redo the branch (with the repo transfer) and want to investigate a larger error handling thought process.

**Comment by rlam3** [comment]
If we are using postcss with gulp-stylus and lost grid.. how do we configure our gulpfile.js to see errorhandling. Thanks!

**Comment by peterramsing** [comment]
@rlam3 Hmmm. Interesting thought. I'd love to try to ensure that LostGrid is pre-processor agnostic as possible but for those using Stylus that sounds promising!

**Comment by corysimmons** [comment]
@rlam3 You can catch any errors any Gulp task throws with https://www.npmjs.com/package/gulp-plumber#optionserrorhandler

**Pull request closed without merging**
