### PR TITLE
WIP: Removes *zoom

### PR DESCRIPTION
**Pull request by peterramsing**
See #194 #135 
- [x] Updates lost-center
- [x] Updates lost-masonry-wrap
- [x] Updates lost-utility
- [ ] Update tests

### CODE REVIEW

**Comment by peterramsing** [comment]
@corysimmons @wyze Do you think that this issue regarding the test is a blocker or something to be addressed in a larger project later?

**Comment by corysimmons** [comment]
Your call. I'd advise against merging stuff that breaks tests in any way unless you have a really thorough understanding of what is breaking the test. /$.02

**Comment by peterramsing** [comment]
@corysimmons Sounds good. I'm going to dive a bit deeper. This is a 7.0 thing so it can certainly wait.

**Comment by wyze** [comment]
You mentioned wanting to test the AST, so I looked into how to approach that. You would need to modify `check.js` and instead of using the `.css` property of the processor, you would want to use `.root.nodes`.

I would probably move the assertion out and do it in each test individually since testing the AST is more involved than a simple string check.

In case you were curious, the reason for the current testing structure as I wasn't sure how people were testing PostCSS plugins, so I checked out a few and saw what they did and mimicked it.

**Comment by peterramsing** [comment]
I was actually just looking at PostCSS's autoprefixer yesterday and you're right-they test the way you made it. I'll look into this further.

**Comment by wbruno** [comment]
what do we need to merge this PR ?

**Comment by peterramsing** [comment]
@wbruno I just need to update the tests. It hasn't been a deal-breaker so I haven't put much focus on it. I can finish it up for the next release.

Are you experiencing any issues with it or just wanting less code?

**Comment by wbruno** [comment]
I have to validate my css, at w3c. CEO orders.
I can help with te tests, let me see.

**Comment by peterramsing** [comment]
@wbruno The gist is that I was sort of hacking the tests around the code. That was right when I took over. I'll look too before I need to duck into the office. Maybe we can get a patch out... or is this a breaking change? Crumbs...

**Comment by peterramsing** [comment]
Because there is no direction mention of IE7 support I don't believe this is a breaking change. Going to run this by a colleague to check my reasoning on that.

**Comment by wbruno** [comment]
Yep! it really doesn't make any sense, keep a ie7 hack, with `calc` and all the others stuffs..

**Comment by peterramsing** [comment]
@wbruno Hehe. This is so old the target branch isn't correct. Whoops. Going to close and open a new PR.

**Pull request closed without merging**
