### PR TITLE
Adds a float to the last cycle of the div in Lost-Column and Lost-Waffle

### PR DESCRIPTION
**Pull request by peterramsing**
- [x] Add this to `lost-column`
- [x] Add this to `lost-waffle`

See #200

### CODE REVIEW

**Comment by peterramsing** [comment]
@bradryanbice - if you want to pull this down and test it to see if it solves your issue you're more than welcome to. I'll get to the `lost-waffle` rule (or someone else can?) in the coming weeks. Hoping 6.7.0 by mid/late January. If only I had more hours in the day. :smile:

**Comment by bradryanbice** [comment]
Thanks all, I'll take a look.

**Comment by peterramsing** [comment]
@bradryanbice Any updates on if this helped? Should be finishing this up soon.

**Comment by bradryanbice** [comment]
The float:right fix worked for me in getting rid of the 1px sliver. However I have not had a chance to test to extensively beyond my initial example.

**Comment by peterramsing** [comment]
@bradryanbice Cool. I'm going to be doing some more tests with 6.7.0 this weekend + coming week but glad to know it at least appears to be on the right track! Thanks for submitting the issue!

**Comment by bradryanbice** [comment]
Absolutely, thanks for being on top of this. Nice to see such great support.

**Comment by peterramsing** [comment]
@bradryanbice Certainly trying to do the best we can. :smile:

**Comment by peterramsing** [comment]
This should be good to go. I want to do some more testing to triple check there are no issues a bit more but this should be good to go.

@bradryanbice Any additional feedback on this?

**Comment by corysimmons** [comment]
:tada:

**Comment by alex-ketch** [comment]
Thought I'd chip in as this seems to be working for me too.
Attached screenshot before and after.

For some reason it was mainly happening on the middle column, even though the widths for the side columns was also 1px short of the parent container's width.

_Before_
Before using 6.7.0

_After_
After using 6.7.0

Of note is that I had to remove `lost-offset`, but could be a consequence of some other styling.

``` css
h1 {
  lost-column: 9/10 1;
  lost-offset: -1/10;
}
```

to

``` css
h1 {
  lost-column: 9/10 1;
}
```

**Edit:** Noticed I was a bit late to the party and it's already been merged :)

**Pull request merged**
