### PR TITLE
Updates all 99 percents to be the same

### PR DESCRIPTION
**Pull request by peterramsing**
# Todo Still:
- [x] Add ability adapt the percentage of the 'rounder'.

**What kind of change is this? (Bug Fix, Feature...)**
Update and refactor

**What is the current behavior (You can also link to an issue)**
Some 99.9%, others 99.999999%

**What is the new behavior this introduces (if any)**
All 99.9%

**Does this introduce any breaking changes?**
Possibly. It should be tested.

**Does the PR fulfill these requirements?**
- [x] Tests for the changes have been added
- [x] Docs have been added or updated

### CODE REVIEW

**Comment by corysimmons** [comment]
From my testing, `99.99%` works well with anything that has gutters between it and `99.99999%` works well with no gutters.

I think there are some edge cases (when nesting a lot and such) that will never be fixed (this will always be a moving target and people will undoubtedly open issues each time this changes) until there is a way to specify these on a local level.

Not trying to market, just trying to show the solution I'm currently exploring to solve this problem. In ant, I'm doing:

``` scss
.foo {
  width:
    sizes(1/3) pluck(1)
    rounder(99.978232%); // notice how it's local to this specific size
}
```

I just bring this up because, again, _whatever target_ (this PR, `99.9%`, included) you try to hit on this is going to cause people issues.

**Comment by peterramsing** [comment]
Yeah...it's a bit of a tricky situation no matter what.

I was exploring some options that used pseudo elements to simulate filling space and might keep playing with the idea...but it might be over engineered.

**Comment by corysimmons** [comment]
> I was exploring some options that used pseudo elements to simulate filling space and might keep playing with the idea...but it might be over engineered.

I love this kind of stuff. Let me know if you ever want to pair on tinkering around with this.

Are you doing the `::after { flexbox margin auto stuff }` on the container or something?

**Comment by peterramsing** [comment]
I was playing with it on the container where the container would simulate a more accurate version of "100%" so that 100% would actually work and any pixel rounding would get caught in this simulated buffer. I'll make some codepens tomorrow if I get a chance with what I was playing with.

**Comment by peterramsing** [comment]
I played with some over engineered solutions but I think @corysimmons has it nailed with just allowing the user to specify the, as Cory calls it, "rounder" inline.

**Pull request merged**
