### PR TITLE
Adds Editor Config to project

### PR DESCRIPTION
**Pull request by peterramsing**
Indent style should be a space
Indent size should be 2

### CODE REVIEW

**Comment by peterramsing** [comment]
This is the "generic" but should other editors that don't support this get their own config? Or should this be done by linting instead?

**Comment by corysimmons** [comment]
I think .editorconfig is perfectly fine.

**Comment by peterramsing** [comment]
I'll merge this after I finalize a way of tracking a changelog. I think this is goo to go, then.

**Comment by corysimmons** [comment]
When you release a new package via NPM, you should make a [release](https://github.com/peterramsing/lost/releases) with changelog notes.

I used to maintain CHANGELOG.md's with all my projects until I noticed I was just copy-pasting everything from my changelog to my release notes. /$.02

**Comment by peterramsing** [comment]
I suppose I mean for the dev cycle, where is the changelog? I could keep the change written on my desktop till the release but that doesn't pass the bus test. :bus:

**Comment by peterramsing** [comment]
If you haven't noticed yet, I'm a man all about the process. :white_check_mark: :smile:

**Comment by corysimmons** [comment]
I'm not sure what you mean by dev cycle. [Good commits](https://github.com/erlang/otp/wiki/Writing-good-commit-messages) should have information regarding what was in the commit, and the releases can be a good overview of those changes.

Are you talking about keeping an actual CHANGELOG file?

**Comment by peterramsing** [comment]
It's a small thing, really. At work we have different holding spots for tickets. After they are merged they get put in a new spot saying they're merged but not released. When releasing you go and see all the tickets merged but not released and add them to the changelog.

You're right in saying the commits should hold the keys, but sometimes they don't. I want a place to know all the features coming down the pipe. I think that an issue for each feature in the milestone is sufficient but want to go slow and smart to ensure process stability.

**Comment by corysimmons** [comment]
For what it's worth, I'm totally not against you having a CHANGELOG. If it helps you in any way, go for it. =)

**Comment by peterramsing** [comment]
I'm going to try this out by using the Milestone

**Pull request merged**
