### PR TITLE
Global Gutter Variable

### PR DESCRIPTION
**Pull request by peterramsing**
**What kind of change is this? (Bug Fix, Feature...)**
New Feature

**What is the new behavior this introduces (if any)**
- [x] New `$lost-gutter` variable that returns the global gutter.
- [x] New `$lost-local-gutter` variable that will take the local gutter if one is set in the declaration. If none is set then it takes the global.

**Does the PR fulfill these requirements?**
- [x] Tests for the changes have been added
- [x] Docs have been added or updated

### CODE REVIEW

**Comment by peterramsing** [comment]
I have the initial local variable working. I just need to update it for some of the other rules and maybe add some more tests for edge cases (then make those tests pass) but this is looking like a solid add for version 8. 👍

**Comment by plesiecki** [comment]
why not use CSS custom properties syntax for variables?

**Comment by peterramsing** [comment]
@plesiecki  Hmm. I see where you're going with that. I want to keep things familiar so I like your thought!

I'm understanding that you're suggesting not to use CSS custom variables but to share that syntax. I don't want to shut the door on that right away but I do see them as different as there would be typical cases where the user is not explicitly setting the gutter value...it's something that could be coming from LostGrid, not the user (i.e. just referencing the default global gutter value of 30px). 

* **Would it be odd to have a CSS custom variable that isn't define anywhere as it's done within the LostGrid transpile?**
* **Would there be any issues where the variable might throw warnings such as if the cssnext plugin was run before LostGrid and it attempts to transpile that variable but there is no definition for it?**
---
I'm prepared to change things up but these were some of the thoughts that came to mind when working through the syntax.
If you feel these are invalid please let me know. If you have a better solution for the `$lost-gutter` variable I'm also not opposed to changing it.

Thanks for the feedback! It's super helpful to talk these things out!

**Comment by peterramsing** [comment]
@plesiecki I'm merging this into `beta` but please let me know your thoughts. Just because it's merged doesn't mean I'm done tweaking it! I just want to move on till we have some updates. 🚀

**Comment by plesiecki** [comment]
I think if you want to introduce variables then CSS custom variables are worth considering. 
For me code like
```css
:root {
  --lost-gutter: 1rem
}
``` 
feels more natural for CSS nowadays than `$lost-gutter`.
If you ask about using CSS custom variables implementation like postcss-custom-properties you probably don't need this (look at postcss-modular-scale for example). 

> Would it be odd to have a CSS custom variable that isn't define anywhere as it's done within the LostGrid transpile?

I guess not. Actually CSS custom props has something called fallback for undefined vars:
```css
color: var(--missing, green);
``` 
> Would there be any issues where the variable might throw warnings such as if the cssnext plugin was run before LostGrid and it attempts to transpile that variable but there is no definition for it?

It may be the case.

**Comment by peterramsing** [comment]
I think keeping with defining the gutter with the `@lost gutter xx` will help keep consistency, but I think it's something I should keep in my head as more users are using he newer syntax for variables. I could see setting LostGrid globals in the root as something down the line instead of the at declarations if that feels like the direction things are going.

Do you think that outputting the gutter as `var(--lost-gutter)` is better than `$lost-gutter`?

**Comment by plesiecki** [comment]
I would opt for the first because it's the css way of using variables. Also I would try to apply the css way for setting the gutter. In the end, it will be available in next major.

**Comment by peterramsing** [comment]
Are you referring to the `column-gap`? http://www.w3schools.com/CSSref/css3_pr_column-gap.asp

Regarding the use of the `var(--lost-gutter)` I think you're right in wanting to ensure that keeping things consistent with `css` is awesome...I just worry that it might be too consistent and cause parsing issues either with additional plugins that use the new syntax.

Also, I think there is a slight difference in that these variables will be parsed by postcss and the `var(--awesome-var)` is sent to the browser to be interpreted.

🤔

**Comment by plesiecki** [comment]
I thought about setting gutter with css custom prop ;) 

Your concerns are totally valid. With notation of custom props the order of plugins may play a role. 

Using a variable in the calc and sending it to the browser could open new possibilities. :thinking:

**Comment by peterramsing** [comment]
Hmmm. Interesting.

Yeah, I get a fair amount of request concerns with the ordering of tools in build processes and so I'm very hesitant to have something add to that complexity especially when many users of LostGrid are new to development.

I think passing a variable into calc for the browser would be interesting for sure...not enough browser support, though. 😔

**Comment by japick** [comment]
Personally I use gulp-sass, so using `$variable-name` feels familiar/normal to me. I think most devs these days are using some kind of preprocessor.

Switching to the custom props syntax could be of benefit from a future-proofing perspective, though.

**Comment by peterramsing** [comment]
Alright...decision time (not that it can't be adapted later).

@plesiecki I love the thought process and thank you for the feedback! LostGrid should be thinking for the future so keep on pushing me and my cranky old ways!

I updated the syntax last night to `$lost-gutter` and `$lost-gutter-local`. Unless during the beta testing these become an issue then this is what will go out in version 8.

### Reasoning
I really like the idea of using css variables but the trouble comes in defining them. The nature of these variables is to take something that is contextual to LostGrid and is transpiled by PostCSS and not something that reaches the browser.

### Future proofing
Presently LostGrid takes numbers + units. In the future it could also take variables so it could take something like `lost-gutter: var(--site-gutter);` and that would then be transpiled out to the browser. I'm hesitant doing this right now because most use-cases still require transpiling of those variables again *and* that's where it causes confusion ensuring that the right plugins are used in the right order.

### Thanks!
Thanks for all the feedback on Twitter, Gitter, email, and here on GitHub! I don't want to make the right decisions for the community and this helps a lot!

**Comment by deanmnz** [comment]
```
$lost-gutter-local: '$lost-gutter-local';
$lost-gutter: '$lost-gutter';
```

Was the only way I could get this to work with SASS.

**Pull request merged**
