### PR TITLE
Add nth-of-type support, optional args order

### PR DESCRIPTION
**Pull request by zgreen**
This PR does two things primarily:
- Addresses https://github.com/peterramsing/lost/issues/192, adding `nth-of-type` support.
- Also addresses https://github.com/peterramsing/lost/issues/213, so that args for `lost-column` and `lost-row` can now be passed optionally/in any order.

All current tests passing and I think it would probably be prudent to add more, but I wanted to submit this so that folks could have a look at it.

### CODE REVIEW

**Comment by zgreen** [comment]
Will look into that Travis error.

**Comment by peterramsing** [comment]
This looks awesome! Would you mind submitting a PR against the 6.7.0 branch? I can do it as well if you'd like.

**Comment by zgreen** [comment]
No problem, just submitted.

**Comment by peterramsing** [comment]
Thanks! I just got to work but I'll follow up with #216 later today.

**Pull request closed without merging**
