### PR TITLE
Adds lost-column: none for unsetting a lost-column rule and enhances README

### PR DESCRIPTION
**Pull request by peterramsing**
Regarding the conversation happening in #150 (unsetting lost-column)

### CODE REVIEW

**Comment by peterramsing** [comment]
@corysimmons What are your thoughts? Too much of a hack?

**Comment by corysimmons** [comment]
Looks good. Care to add a test?

**Comment by peterramsing** [comment]
I'll look into that. I'm flying back home tonight so I'll write those on the plane if I have any battery left.

**Comment by peterramsing** [comment]
@corysimmons Do you have any thoughts on the syntax? `lost-column: none` work?
I'll also add in documentation for it.

**Comment by corysimmons** [comment]
Yeah `lost-column: none` seems fine.

**Comment by peterramsing** [comment]
"unset"? https://developer.mozilla.org/en-US/docs/Web/CSS/unset

**Comment by corysimmons** [comment]
- none
- unset
- reset
- inherit

I'm fine with any of those. =)

**Comment by peterramsing** [comment]
When I am working on the final pieces on the plane tonight I'll see what feels the best. :) I still want to test some more odd use cases...but it looks like it's working well.

**Comment by peterramsing** [comment]
Bah–I'll look at why that failed and fix it...but it might have to wait till morning...

**Comment by peterramsing** [comment]
@corysimmons Back to you. Sorry about the copy-pasta...it's been a long weekend/early week.

**Comment by peterramsing** [comment]
Closing this in leu of #211

**Pull request closed without merging**
