### PR TITLE
WIP: Typings and configuration for migration to typescript

### PR DESCRIPTION
**Pull request by BarryThePenguin**
**What kind of change is this?**

Typescript!

**What is the current behavior (You can also link to an issue)**

No Typescript :cry: 

**What is the new behavior this introduces (if any)**

Typescript

**Does this introduce any breaking changes?**

The resulting javascript should be equivalent so no breaking changes expected

**Does the PR fulfill these requirements?**
- [ ] Tests for the changes have been added
- [ ] Docs have been added or updated

Seeing as though postcss offers type definitions for plugin developers I thought it would be a good idea to utilise them. The main changes include:
- renaming src file extensions to .ts
- use Typescript exports in library modules
- npm scripts to handle compilation, tests and coverage mapping
- exclude compiled files from git
- include compiled files in npm packages

~~The big blocker is postcss/postcss#808, the type definition for postcss doesn't currently work well with CommonJS modules~~

**todo**:
- [x] Typescript tests
- [ ] Enable `noImplicitAny`

### CODE REVIEW

**Comment by peterramsing** [comment]
@BarryThePenguin This looking like it's going to be a lot of good fun. Thanks for taking this on. From what it looks like, we are still blocked by postcss/postcss#808. Is this still the case on your end?

**Comment by BarryThePenguin** [comment]
Yeah.. will be blocked until the typings for postcss are corrected. I'm happy to keep an eye on it

**Comment by peterramsing** [comment]
@BarryThePenguin Cool. I'm going to be progressing with some more changes so hopefully, there isn't a nasty merge conflict. I'll keep an eye on things as well.

**Comment by BarryThePenguin** [comment]
I can take care of it if it gets too nasty. Pretty used to tidying up merge conflicts :wink: I've got level :eight: rebasing skills

**Comment by BarryThePenguin** [comment]
So this looks good now thanks to postcss@5.1.0 which fixes the typescript imports

The failing build is a result of the coverage checks on node 0.10, SitePen/remap-istanbul#64 has the details.

**Comment by peterramsing** [comment]
@BarryThePenguin I'm going to do a bump on `master` for PostCSS (and others) to ensure all dependencies are up to date. 👍🏻

**Comment by peterramsing** [comment]
I'm going to close this for now. We'll return to this later.

**Comment by BarryThePenguin** [comment]
Looks like the fix for CI and node 0.10 landed 7 days ago ;)

**Comment by peterramsing** [comment]
@BarryThePenguin Cool! Let's revisit this once we deprecate previous versions of Node, eh?

**Comment by BarryThePenguin** [comment]
Cool 👍

**Pull request closed without merging**
